services:
  payment-page:
    image: ghcr.io/necko-moe/necko3-payment-page:latest
    container_name: necko3-payment-page
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:3737:80"
